from typing import List, Tuple, Optional, Dict
import numpy as np
from scipy.stats import spearmanr
from models.schemas import RankingEvaluation


class RankingEvaluator:
    """
    Evaluates and compares rankings generated by different recommendation approaches
    using Spearman Rank Correlation.
    Useful for assessing rank concordance between Content-Based and Collaborative Filtering.
    """

    @staticmethod
    def calculate_spearman(
        scores_a: List[float],
        scores_b: List[float],
    ) -> Tuple[Optional[float], Optional[float]]:
        """
        Calculates Spearman rank correlation coefficient and associated two-sided p-value
        between two ranking score vectors.
        """
        if len(scores_a) < 3 or len(scores_b) < 3 or len(scores_a) != len(scores_b):
            return None, None

        # Check for zero variance
        if np.all(np.isclose(scores_a, scores_a[0])) or np.all(np.isclose(scores_b, scores_b[0])):
            return 0.0, 1.0

        try:
            res = spearmanr(scores_a, scores_b)
            # scipy.stats.spearmanr returns a tuple or SpearmanrResult object
            corr = float(res.statistic if hasattr(res, "statistic") else res[0])
            p_val = float(res.pvalue if hasattr(res, "pvalue") else res[1])

            if np.isnan(corr) or np.isnan(p_val):
                return None, None

            return round(corr, 4), round(p_val, 4)
        except Exception:
            return None, None

    @classmethod
    def evaluate_rankings(
        cls,
        content_scores: List[float],
        collaborative_scores: List[float],
    ) -> RankingEvaluation:
        """
        Calculates the Spearman rank correlation and returns an enriched evaluation schema.
        """
        corr, p_val = cls.calculate_spearman(content_scores, collaborative_scores)

        if corr is None:
            return RankingEvaluation(
                spearman_correlation=None,
                p_value=None,
                interpretation="Insufficient variance or candidate count to compute rank correlation.",
            )

        # Interpret the degree of correlation
        if corr > 0.6:
            interpretation = "Strong rank concordance: Content and collaborative engines strongly align."
        elif corr > 0.2:
            interpretation = "Moderate positive concordance: Both models agree on leading themes."
        elif corr >= -0.2:
            interpretation = "Orthogonal diversity: Collaborative signals identify novel papers beyond keyword overlap."
        else:
            interpretation = "Inverse rank divergence: Models prioritize markedly distinct research attributes."

        return RankingEvaluation(
            spearman_correlation=corr,
            p_value=p_val,
            interpretation=interpretation,
        )
